//application state is generated by Reducer functions
//Redux serves to construct application state
export default function () {
  return [
    {title:'Atlas Unshrugged', pages:800},
    {title:'Pride and Prejudice',pages:500},
    {title:'Harry Potter',pages:600},
    {title:'Lord of the Rings',pages:450},
    {title:'The Da Vinci Code',pages:380}
  ]
}
